<?php include_once('header.php') ?>
<main>
    <h1>Delicious. Customizable. Yours.</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia ducimus animi delectus tenetur rerum voluptatibus, dolorem laborum assumenda voluptas pariatur sunt expedita magni molestiae porro id autem explicabo dolor corporis!</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum eveniet quod ipsa laudantium voluptate, error facilis labore doloremque quas illum illo. Harum fuga illo quae velit ex nulla cupiditate obcaecati.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore incidunt, nobis labore eveniet nesciunt, cumque perspiciatis necessitatibus quam voluptas facere, numquam qui officia? Officia voluptate iure assumenda nulla! Similique, deserunt.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corrupti, error. Temporibus dolorem minus nihil consequatur iste ipsa inventore. Veritatis minus blanditiis laudantium commodi labore odit maiores nam fugiat iure cupiditate?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia ducimus animi delectus tenetur rerum voluptatibus, dolorem laborum assumenda voluptas pariatur sunt expedita magni molestiae porro id autem explicabo dolor corporis!</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum eveniet quod ipsa laudantium voluptate, error facilis labore doloremque quas illum illo. Harum fuga illo quae velit ex nulla cupiditate obcaecati.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore incidunt, nobis labore eveniet nesciunt, cumque perspiciatis necessitatibus quam voluptas facere, numquam qui officia? Officia voluptate iure assumenda nulla! Similique, deserunt.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corrupti, error. Temporibus dolorem minus nihil consequatur iste ipsa inventore. Veritatis minus blanditiis laudantium commodi labore odit maiores nam fugiat iure cupiditate?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia ducimus animi delectus tenetur rerum voluptatibus, dolorem laborum assumenda voluptas pariatur sunt expedita magni molestiae porro id autem explicabo dolor corporis!</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum eveniet quod ipsa laudantium voluptate, error facilis labore doloremque quas illum illo. Harum fuga illo quae velit ex nulla cupiditate obcaecati.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore incidunt, nobis labore eveniet nesciunt, cumque perspiciatis necessitatibus quam voluptas facere, numquam qui officia? Officia voluptate iure assumenda nulla! Similique, deserunt.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corrupti, error. Temporibus dolorem minus nihil consequatur iste ipsa inventore. Veritatis minus blanditiis laudantium commodi labore odit maiores nam fugiat iure cupiditate?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia ducimus animi delectus tenetur rerum voluptatibus, dolorem laborum assumenda voluptas pariatur sunt expedita magni molestiae porro id autem explicabo dolor corporis!</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum eveniet quod ipsa laudantium voluptate, error facilis labore doloremque quas illum illo. Harum fuga illo quae velit ex nulla cupiditate obcaecati.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore incidunt, nobis labore eveniet nesciunt, cumque perspiciatis necessitatibus quam voluptas facere, numquam qui officia? Officia voluptate iure assumenda nulla! Similique, deserunt.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corrupti, error. Temporibus dolorem minus nihil consequatur iste ipsa inventore. Veritatis minus blanditiis laudantium commodi labore odit maiores nam fugiat iure cupiditate?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia ducimus animi delectus tenetur rerum voluptatibus, dolorem laborum assumenda voluptas pariatur sunt expedita magni molestiae porro id autem explicabo dolor corporis!</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum eveniet quod ipsa laudantium voluptate, error facilis labore doloremque quas illum illo. Harum fuga illo quae velit ex nulla cupiditate obcaecati.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore incidunt, nobis labore eveniet nesciunt, cumque perspiciatis necessitatibus quam voluptas facere, numquam qui officia? Officia voluptate iure assumenda nulla! Similique, deserunt.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corrupti, error. Temporibus dolorem minus nihil consequatur iste ipsa inventore. Veritatis minus blanditiis laudantium commodi labore odit maiores nam fugiat iure cupiditate?</p>
</main>
<?php include_once('footer.php') ?>